Traceback (most recent call last):
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\jupyter_core\utils\__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\nreul.IFR\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
plt.ion()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m rcParams, cycler
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

File [1;32m~\.conda\envs\JB\lib\site-packages\matplotlib\__init__.py:108[0m
[0;32m    105[0m [38;5;28;01mimport[39;00m [38;5;21;01mtempfile[39;00m
[0;32m    106[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m
[1;32m--> 108[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m
[0;32m    109[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpackaging[39;00m[38;5;21;01m.[39;00m[38;5;21;01mversion[39;00m [38;5;28;01mimport[39;00m parse [38;5;28;01mas[39;00m parse_version
[0;32m    111[0m [38;5;66;03m# cbook must import matplotlib only within function[39;00m
[0;32m    112[0m [38;5;66;03m# definitions, so it is safe to import from it here.[39;00m

[1;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

